# Generated by Django 3.0.2 on 2020-02-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinformation',
            name='release_date',
            field=models.DateField(),
        ),
    ]
